### ISSUE TITLE
Commit access

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/libembroidery#114]
Can I be granted commit access to the libembroidery repository? Since all of my commits are getting accepted, I think my vision for the software matches yours.

Cheers,
Robin

**Comment by JoshVarga** [comment]
Yeah I invited you probably a month ago. Let me check on that. I wasn't
sure why you didn't accept.

**Comment by JoshVarga** [comment]
[image: image.png]

**Comment by JoshVarga** [comment]
I just double checked and you have an invite pending on both libembroidery
and embroidermodder

**Comment by robin-swift** [comment]
Just tried, they timed out because I missed them. Can you send new ones please?

**Comment by JoshVarga** [comment]
I just re-invited you to both

**Comment by robin-swift** [comment]
Thanks
