### ISSUE TITLE
offset error in some pes files 

### ISSUE THREAD

**Issue by fabricocouto** [Embroidermodder/libembroidery#115]
![image](https://user-images.githubusercontent.com/20323161/135260590-34c721d0-d728-4700-9156-c3ee3e727898.png)

a few months ago I discovered an error reading the pes file.
in some certain files it is pecstart + 533 and in others it follows the pattern used for years which is pecstart + 532.
the biggest problem is figuring out why certain files are 533 

segue file in pec start + 533

[simbolo escola pequeno.zip](https://github.com/Embroidermodder/libembroidery/files/7251513/simbolo.escola.pequeno.zip)

**Comment by JoshVarga** [comment]
Fixed.
