### ISSUE TITLE
[Feature request] Write ZSK format

### ISSUE THREAD

**Issue by vinibali** [Embroidermodder/libembroidery#123]
Hello there!

This is such a great project. Is there any way to get the zsk format supported?
If so, I can help with the testing, one of my friends has a working machine from the 1980s!

**Comment by robin-swift** [comment]
@vinibali 

I've written in support for ZSK, but it is as yet untested.

If on using the command:

```
embroider your_input.dst your_output.zsk
```

then loading the file on your machine you find any problems please post a new issue. Photographs of the embroidery and design would help us identify the problem.

Cheers, Robin
