### ISSUE TITLE
Error Compounding In Most Writers.

### ISSUE THREAD

**Issue by tatarize** [Embroidermodder/libembroidery#125]
```C
while(stitches)
    {
        dx = stitches->stitch.xx * 10.0 - xx;
        dy = stitches->stitch.yy * 10.0 - yy;
        xx = stitches->stitch.xx * 10.0;
        yy = stitches->stitch.yy * 10.0;
        flags = stitches->stitch.flags;
        jefEncode(b, (char)roundDouble(dx), (char)roundDouble(dy), flags);
...
```

This mechanism doesn't work. The error is introduced during the rounding of the dx, dy and that isn't tracked. The values of xx, yy, need to be the needle position given the summation of the actual dx, dy values given. 

It needs to have the value of xx, yy the sum of the dx, dy values. And to round at the calculation of dx, dy.

**Comment by robin-swift** [comment]
fixed in commit e5d5f1f59ce
