### ISSUE TITLE
Crash on SVG import

### ISSUE THREAD

**Issue by ali1234** [Embroidermodder/libembroidery#127]
Example SVG file which crashes the converter:

http://al.robotfuzz.com/~al/random/drawing.svg

**Comment by robin-swift** [comment]
This link is dead, so I'll close this issue.

**Comment by ali1234** [comment]
Here's a copy of the svg.
[drawing.svg.zip](https://github.com/Embroidermodder/libembroidery/files/7493279/drawing.svg.zip)
