### ISSUE TITLE
Opening SVG files

### ISSUE THREAD

**Issue by DwerewolfT** [Embroidermodder/libembroidery#128]
Sirs,

I have managed to compile Embroidermodder2 on Ubuntu 14.04 64bit using Qt5 and successfully transferred a few of the sample files to PES format and embroidered them on my Brother Innov-is V7.

However every time I attempt to open any SVG file Embroidermodder2 crashes.

Is this because of 'work in progress' or do I have something wrong?

My main interest at this time is to convert jpg to svg via inkscape then embroider using Embroidermodder which isn't going to work if I can't import an svg file.

Help please.

regards

**Comment by robin-swift** [comment]
I think the strongest discussion on SVG is on #136 so I'm closing this as a duplicate
