### ISSUE TITLE
Multiple version of an embroidery format?

### ISSUE THREAD

**Issue by x2nie** [Embroidermodder/libembroidery#139]
Is there a way to distict multiple version from each embroidery format (if any)?
For instance: 
Many Brother's machine support *.PES file,
but internally they only recognize a specific version of PES.
Let say Brother model X accepts PES ver 001, while Brother model Y accepts PES ver 006.

Okay, not every embroidery format has several version. But some of it has.

So, how we can instruct libembroidery to save to .PES in specific version?

**Comment by robin-swift** [comment]
I'm moving this to the "ideas" section of [the manual](manual.md).
