### ISSUE TITLE
Fix thread-color files

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/libembroidery#163]
Copied from old to do list.

**Comment by robin-swift** [comment]
Jef threads #122 was fixed, so that's 1 down.

**Comment by tatarize** [comment]
When I read this todo note, I read it to mean fix the thread/color files. So the file reading and writing for just thread color. Those are going to be `.edr` `.col` `.ini` and I think one other format. These formats do not actually save other information they are only thread-color files.

**Comment by robin-swift** [comment]
I'm not sure what the todo item was for then? Fix them how?

Should I close this as too vague?
