### ISSUE TITLE
Fix issues with DST (VERY important that DST work well)

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/libembroidery#172]
Copied from old to do list.

**Comment by tatarize** [comment]
This is vague and I'm pretty sure despite lacking sequins the DST reader and writer in libembroidery was pretty good. Even while it was in used in Inkstitch until they felt too many growing pains and I finished up pyembroidery for that project the dst format was known to be pretty good. I personally checked it for #125 (Error Compounding) and unlike the other writers it did fine.

**Comment by robin-swift** [comment]
Ok, that was probably just not checked off the to do list I copied these from. I'll close the issue.
