### ISSUE TITLE
Rebuild LISP system for function encoding

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/libembroidery#205]
See the contents of `assets/designs/`.

The idea is that by using LISP for user submitted functions we can have a much simpler data sanitation process.

Note that we're not supporting general LISP expressions (we may need to find out what this subset would be called) and they are loaded as YAML because they are only one input, one output functions as strings.

**Comment by robin-swift** [comment]
`libembroidery` may not actually use any lisp features directly, but since EM2 needs some method of user input for functions the interpreter will be part of this code.

**Comment by tatarize** [comment]
Pyembroidery for python already exists. It's basically libembroidery re-written for python along with some needed re-encoding technologies to ensure compatibility between different formats.

**Comment by petrsorfa** [comment]
> Pyembroidery

Nice! Thanks for the pointer. Although Robin is implementing is a scripting language within the frontend, which is a bit different.

**Comment by robin-swift** [comment]
This is resolved by TinyScheme see https://github.com/Embroidermodder/TinyScheme
