### ISSUE TITLE
erro file read

### ISSUE THREAD

**Issue by fabricocouto** [Embroidermodder/libembroidery#76]
now it is possible to generate the dll using swing
but to an error in it using the convert method generate the following error in the image 
![Sem título](https://user-images.githubusercontent.com/20323161/133093653-ccff7cd8-7fd0-46d4-a56f-2c1929bc2532.png)

**Comment by fabricocouto** [comment]
also always returns the error
Attempt to read or write to protected memory. This is usually an indication that other memory is bad.

**Comment by JoshVarga** [comment]
I rebuilt the DLL try this...
https://drive.google.com/file/d/1JsUlTYjofIw45tisZ4RNVLB7Vp1RVvjL/view?usp=sharing
it works for me
