### ISSUE TITLE
memory error protected

### ISSUE THREAD

**Issue by fabricocouto** [Embroidermodder/libembroidery#80]
hello, the dll is being generated without errors using swig and visual studio 2019 c.
but when I make her call through csharp she gives memory error  in embpathern readprotected I've done many tests as admin and on another windows computer all with the same lock 

![image](https://user-images.githubusercontent.com/20323161/133317232-304e808f-cf4e-4d0a-8329-8d7f83ef5f68.png)

**Comment by fabricocouto** [comment]
![image](https://user-images.githubusercontent.com/20323161/133317733-fe1acd1f-0dec-460d-9021-4d969cdfb672.png)

**Comment by robin-swift** [comment]
This comes under shipping the new DLL (a general goal of 1.0), I'm closing as it's unclear that this will remain relevant.
